# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_filter_algorithm <- function(inpLIST, nrep) {
    .Call('spThin_rcpp_filter_algorithm', PACKAGE = 'spThin', inpLIST, nrep)
}

rcpp_thin_algorithm <- function(lon, lat, thin_par, reps, great_circle_distance) {
    .Call('spThin_rcpp_thin_algorithm', PACKAGE = 'spThin', lon, lat, thin_par, reps, great_circle_distance)
}

